const appLinks = {
  Dashboard: "/",
  Orders: "/orders",
  Delivery: "/delivery",
  Inventory: "/inventory",
  Books: "/books",
  Employees: "/employees",
  Sites: "/sites",
  SiteDetail: "/sites/:siteId/detail",
  EmployeeDetail: "/employees/:employeeId/detail",
  Pay: "/pay/:orderId",
  OrdersDetail: "/orders/:orderId/detail",
  BuildersPlant: "/builders-plant",
  ShellEquipment: "/shell-equipment",
  BuildersPlantDetail: "/builders-plant/:builderId/detail",
  BuildersPlantSupplier: "/builders-plant/supplier",
  BuildersContractorInput: "/builders-contractor-input",
  BuildersPlantOrderSummary: "/builders-plant/order-summary",
  BuildersPlantIdentification: "/builders-plant-identification",
  BuildersPlantCategoryDetail: "/category/:categoryId/detail",
  ShellEquipmentDetail: "/shell/:shellItemId/inventory",
  OrderAggregate: "/order/:shellItemId/aggregate",
  BuildersPlantSupplierDetail: "/supplier/:supplierId/detail",
  BuildersContractorInputDetail: "/contractor-input/:contractorInputId/detail",
  ShellEquipmentSuppliers: "/shell-equipment-suppliers",
  Settings: "/settings",
};

export { appLinks };
